[package]
name = "safe-buffer"
version = "0.1.0"
edition = "2021"
description = "Out of memory safe chunked binary buffer"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fallible_collections = "0.4.9"
