[package]
name = "safe-buffer"
version = "0.4.0"
edition = "2021"
description = "Out of memory safe chunked binary buffer"
license = "MIT"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
rand = "0.9.0-alpha.2"